/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AgendaController;
import Model.Agenda;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ROMULOGIOVANINNIDEME
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private final DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    private AgendaController controller;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoAgenda = new javax.swing.JTextPane();
        adicionarNovo = new javax.swing.JButton();
        editarDaAgenda = new javax.swing.JButton();
        deletarDaAgenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoAgenda.setEditable(false);
        jScrollPane1.setViewportView(textoAgenda);

        adicionarNovo.setText("Adicionar Novo");
        adicionarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarNovoActionPerformed(evt);
            }
        });

        editarDaAgenda.setText("Editar");
        editarDaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDaAgendaActionPerformed(evt);
            }
        });

        deletarDaAgenda.setText("Deletar");
        deletarDaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarDaAgendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Agenda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adicionarNovo)
                                .addGap(18, 18, 18)
                                .addComponent(editarDaAgenda)
                                .addGap(18, 18, 18)
                                .addComponent(deletarDaAgenda))
                            .addComponent(jLabel1))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarNovo)
                    .addComponent(editarDaAgenda)
                    .addComponent(deletarDaAgenda))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarNovoActionPerformed
    if (controller != null) {
        controller.adicionar();
        controller.atualizarTela();
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarNovoActionPerformed
    }
    private void editarDaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDaAgendaActionPerformed
    if (controller != null) {
        controller.editar();
        controller.atualizarTela();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_editarDaAgendaActionPerformed

    private void deletarDaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarDaAgendaActionPerformed
    if (controller != null) {
        controller.deletar();
        controller.atualizarTela();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_deletarDaAgendaActionPerformed


    public javax.swing.JTextPane getTextoAgenda() {
        return textoAgenda;
}
    
    public String getTexto() {
    return textoAgenda.getText();
}
    public void setTexto(String texto) {
    textoAgenda.setText(texto);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Agenda model = new Agenda();
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(() ->  {
        
        TelaInicial tela = new TelaInicial();
        AgendaController controller = new AgendaController(model, tela);
        controller.atualizarTela();  
        tela.setVisible(true);
    });
}
    public void setController(AgendaController controller) {
    this.controller = controller;
    }

    

 
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarNovo;
    private javax.swing.JButton deletarDaAgenda;
    private javax.swing.JButton editarDaAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textoAgenda;
    // End of variables declaration//GEN-END:variables
}
