/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AgendaController;
import Model.DiarioService;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ROMULOGIOVANINNIDEME
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private final DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    
    private DiarioService diario = new DiarioService();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        atualizarTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoAgenda = new javax.swing.JTextPane();
        adicionarNovo = new javax.swing.JButton();
        editarDaAgenda = new javax.swing.JButton();
        deletarDaAgenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoAgenda.setEditable(false);
        jScrollPane1.setViewportView(textoAgenda);

        adicionarNovo.setText("Adicionar Novo");
        adicionarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarNovoActionPerformed(evt);
            }
        });

        editarDaAgenda.setText("Editar");
        editarDaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDaAgendaActionPerformed(evt);
            }
        });

        deletarDaAgenda.setText("Deletar");
        deletarDaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarDaAgendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Agenda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adicionarNovo)
                                .addGap(18, 18, 18)
                                .addComponent(editarDaAgenda)
                                .addGap(18, 18, 18)
                                .addComponent(deletarDaAgenda))
                            .addComponent(jLabel1))
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarNovo)
                    .addComponent(editarDaAgenda)
                    .addComponent(deletarDaAgenda))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarNovoActionPerformed
    String texto = JOptionPane.showInputDialog(this, "Digite o texto:");
    if (texto == null || texto.trim().isEmpty()) return;

    try {
        String dataStr = JOptionPane.showInputDialog(this, "Digite a data do evento (yyyy-MM-dd HH:mm):");
        if (dataStr == null || dataStr.trim().isEmpty()) return;

        LocalDateTime dataEvento = LocalDateTime.parse(dataStr, formatoData);

        diario.escreverNovo(texto, dataEvento);

        atualizarTela();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar o evento! Verifique o formato da data: yyyy-MM-dd HH:mm");
    }    // TODO add your handling code here:
    }//GEN-LAST:event_adicionarNovoActionPerformed

    private void editarDaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDaAgendaActionPerformed
    try {
            List<String> linhas = diario.lerLinhas();
            if (linhas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Diário vazio.");
                return;
            }

            String numero = JOptionPane.showInputDialog(this, "Número da entrada para editar:");
            if (numero == null) return;

            int idx = Integer.parseInt(numero) - 1;

            if (idx < 0 || idx >= linhas.size()) {
                JOptionPane.showMessageDialog(this, "Entrada inválida.");
                return;
            }

            String novo = JOptionPane.showInputDialog(this, "Novo texto:");
            if (novo == null || novo.trim().isEmpty()) return;

            diario.editarEntrada(idx, novo);
            atualizarTela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao editar entrada.");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_editarDaAgendaActionPerformed

    private void deletarDaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarDaAgendaActionPerformed
    try {
            List<String> linhas = diario.lerLinhas();
            if (linhas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Diário vazio.");
                return;
            }

            String numero = JOptionPane.showInputDialog(this, "Número da entrada para deletar:");
            if (numero == null) return;

            int idx = Integer.parseInt(numero) - 1;

            diario.apagarEntrada(idx);
            atualizarTela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar entrada.");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_deletarDaAgendaActionPerformed


private void atualizarTela() {
   try {
        List<String> linhas = diario.lerLinhas();
        StyledDocument doc = textoAgenda.getStyledDocument();
        doc.remove(0, doc.getLength()); // limpa

        for (int i = 0; i < linhas.size(); i++) {
            String linha = linhas.get(i);
            String[] partes = linha.split("\\|", 2);
            String dataStr = partes.length > 0 ? partes[0] : "";
            String texto = partes.length > 1 ? partes[1] : "";

            LocalDateTime dataEvento;
            try {
                dataEvento = LocalDateTime.parse(dataStr, formatoData);
            } catch (Exception ex) {
                // linha com formato inválido: exibe normal (sem cor)
                doc.insertString(doc.getLength(), (i+1) + ") " + linha + "\n", null);
                continue;
            }

            long minutosRest = ChronoUnit.MINUTES.between(LocalDateTime.now(), dataEvento);
            String exibicao = (i + 1) + ") " + dataStr + " - " + texto + "\n";

            SimpleAttributeSet estilo = new SimpleAttributeSet();
            if (minutosRest <= 30 && minutosRest >= 0) {
                StyleConstants.setForeground(estilo, Color.RED);
            }

            doc.insertString(doc.getLength(), exibicao, estilo);
        }

    } catch (Exception e) {
        textoAgenda.setText("Erro ao carregar o diário.");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    public void setController(AgendaController controller) {
    this.controller = controller;
}
    private AgendaController controller;
    
    public String getTexto() {
    return textoAgenda.getText();
}
    public void setTexto(String texto) {
    textoAgenda.setText(texto);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarNovo;
    private javax.swing.JButton deletarDaAgenda;
    private javax.swing.JButton editarDaAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textoAgenda;
    // End of variables declaration//GEN-END:variables
}
